{{- range $name, $cluster := .Values.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-cluster
  namespace: {{ $.Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: {{ $name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
stringData:
  name: {{ $name | quote }}
  server: {{ $cluster.server | quote }}
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": {{ $cluster.caData | quote }}
      }
    }
{{- end }}
